const queries = {
  base: "select id_match as 'id', h.team_name as 'homeTeam', h.team_logo as 'homeTeamLogo', v.team_name as 'visitingTeam', v.team_logo as 'visitingTeamLogo', TIME_FORMAT(match_date," + '"%H:%i"' + ") as 'time', DATE_FORMAT(match_date," + '"%d/%m"' + ") as 'day', i.instance_name as 'instanceName', i.instance_detail as 'instanceDetail' from matches m join teams h on (h.id_team = m.id_home_team) join teams v on (v.id_team = m.id_visiting_team) join competitions c on (m.id_competition = c.id_competition) join instances i on (i.id_instance = m.id_instance) where c.id_competition = ",
  today: "select id_match as 'id', h.team_name as 'homeTeam', h.team_logo as 'homeTeamLogo', v.team_name as 'visitingTeam', v.team_logo as 'visitingTeamLogo', TIME_FORMAT(match_date," + '"%H:%i"' + ") as 'time', DATE_FORMAT(match_date," + '"%d/%m"' + ") as 'day', competition_name, i.instance_name as 'instanceName', i.instance_detail as 'instanceDetail' from matches m join teams h on (h.id_team = m.id_home_team) join teams v on (v.id_team = m.id_visiting_team) join competitions c on (m.id_competition = c.id_competition) join instances i on (i.id_instance = m.id_instance) where match_date = (select CURDATE())",
  competitions: "select id_competition as 'key', competition_name as 'name', is_local as 'isLocal', has_brackets as 'hasBrackets', has_positions_table as 'hasPositionsTable', has_groups as 'hasGroups' from competitions",
  table: "select pt.*, t.team_name from positions_table pt join teams t on (t.id_team = pt.id_team) where team_group is null and id_competition =",
  groups: "select distinct team_group as 'group' from positions_table where id_competition =",
  groupsTeams: "select pt.*, t.team_name from positions_table pt join teams t on (t.id_team = pt.id_team) where team_group is not null and id_competition =",
  bracketOne: "select t1.team_name as 'team1', t1.team_logo as 'team1Logo', t2.team_name as 'team2', t2.team_logo as 'team2Logo', i.instance_name as 'instance', i.instance_detail as 'instanceDetail' from brackets b join teams t1 on (t1.id_team = b.id_team_1) join teams t2 on (t2.id_team = b.id_team_2) join instances i on (i.id_instance = b.id_instance) where b.bracket = 1 and b.id_competition =",
  bracketTwo: "select t1.team_name as 'team1', t1.team_logo as 'team1Logo', t2.team_name as 'team2', t2.team_logo as 'team2Logo', i.instance_name as 'instance', i.instance_detail as 'instanceDetail' from brackets b join teams t1 on (t1.id_team = b.id_team_1) join teams t2 on (t2.id_team = b.id_team_2) join instances i on (i.id_instance = b.id_instance) where b.bracket = 2 and b.id_competition =",
  bracketsFinal: "select t1.team_name as 'team1', t1.team_logo as 'team1Logo', t2.team_name as 'team2', t2.team_logo as 'team2Logo', i.instance_name as 'instance', i.instance_detail as 'instanceDetail' from brackets b join teams t1 on (t1.id_team = b.id_team_1) join teams t2 on (t2.id_team = b.id_team_2) join instances i on (i.id_instance = b.id_instance) where b.bracket = 3 and b.id_competition ="
}

module.exports = queries;
